# Generated by Django 5.2.3 on 2025-06-28 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caftan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer name')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Customer email')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Customer phone')),
                ('shipping_address', models.TextField(verbose_name='Shipping address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total price')),
                ('tracking_code', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Tracking code')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Status name')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('caftan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caftan.caftan', verbose_name='Caftan')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderstatus', verbose_name='Order status'),
        ),
    ]
